### PR TITLE
improvements to dplyr-Spatial.r

### PR DESCRIPTION
**Pull request by jlegewie**
Hey,

I followed the discussion on the initial gist and always wanted to contribute my own take. Here are a couple of improvements (maybe not) for dplyr-Spatial.r but you should check each of them.

1) Improved performance for `select_.Spatial` and `filter_.Spatial`
2) Removed transmute. I don't think it's necessary to create a separate method because it just relies on `mutate` and `select`
3) Your version of `filter_.Spatial` added a variable. Not sure why. This one doesn't.
4) What does `summarise_.Spatial` do considering that group_by doesn't work?
5) Added `left_join. Spatial`. The other joins should be easy as well. In my code, I also do `left_join.SpatialLinesDataFrame <- left_join.SpatialDataFrame`. Not sure how you handle that do maybe you have to change something else in a different file. 

**ERROR**: Just saw an error in my pull-request. `select_.Spatial` should now take a `.dots` argument so that the function definition should be `select_.Spatial <- function (.data, ..., .dots) { ...`. If you end up merging this, make sure to correct that.

### CODE REVIEW

**Comment by mdsumner** [comment]
Thanks for this!

I can't get to it right now but I will soon. 

Re 4) it's a good question, to me it was "the limit" of how far you can go with Spatial objects as they are, and a reasonable illustration of simply merging all objects into one - it just collapses to a single-row Spatial*DataFrame.

**Comment by jlegewie** [comment]
I thought about `group_by` + `summarize` for a while and I think the only possibility would be that it creates unions for the spatial polygons and summarizes the data as usual. But that get's much more involved.

**Comment by mdsumner** [comment]
I can't merge this as-is, we cannot use the unexported dplyr:::select_impl - thanks but I'll have to take a closer look when I can get back to it.

**Comment by jlegewie** [comment]
Of course, I mainly wanted to start a discussion and I am not always sure myself about the best approach. Why can't you use `dplyr:::select_impl`? The tripple colon explicitly access unexported functions, no?

**Comment by mdsumner** [comment]
Ah I see, I am fumbling around a bit, I appreciate the input. You cannot
use unexported functions and pass check. I will have to spend more time
understanding nse in dplyr.
BTW I added group_by to master for Spatial, appreciate any testing.

Cheers, Mike

On Sat, 30 Apr 2016, 03:45 Joscha Legewie <notifications@github.com> wrote:

> Of course, I mainly wanted to start a discussion and I am not always sure
> myself about the best approach. Why can't you use dplyr:::select_impl?
> The tripple colon explicitly access unexported functions, no?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/mdsumner/spbabel/pull/10#issuecomment-215827270>
>
-- 
Dr. Michael Sumner
Software and Database Engineer
Australian Antarctic Division
203 Channel Highway
Kingston Tasmania 7050 Australia

**Comment by mdsumner** [comment]
I've incorporated your fixes into the master branch, some things couldn't be done, but some of that may be me misunderstanding. btw, group_by is now implemented and always unions grouped geometries together by 1) decomposing to sptable 2) badging grouped branches with the same id 3) recomposing as Spatial.

**Pull request closed without merging**
